// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    '20190427-在usg上將vlan流量導向openvpn': typeof import('./components/posts/2019-04-27-在usg上將vlan流量導向openvpn.md')['default']
    '20190427-在vestacp的mailServer設定兩個ssl憑證': typeof import('./components/posts/2019-04-27-在vestacp的mail-server設定兩個ssl憑證.md')['default']
    '20190430-如何使用vpn觀看日本netflix？': typeof import('./components/posts/2019-04-30-如何使用vpn觀看日本netflix？.md')['default']
    '20190505-超快速！在日本AmazonEc2-架設OpenvpnServer！！': typeof import('./components/posts/2019-05-05-超快速！在日本-amazon-ec2-架設-openvpn-server！！.md')['default']
    '20190505Macosおすすめのアプリ「istatMini」': typeof import('./components/posts/2019-05-05-macosおすすめのアプリ「istat-mini」.md')['default']
    '20190508-【javascript】javascript-入門篇-學徒的試煉-最終作業': typeof import('./components/posts/2019-05-08-【javascript】javascript-入門篇-學徒的試煉-最終作業.md')['default']
    '20190509-【javascript】js地下城1f9x9乘法表': typeof import('./components/posts/2019-05-09-【javascript】js地下城-1f-9x9乘法表.md')['default']
    '20190511-【javascript】js地下城2f-時鐘': typeof import('./components/posts/2019-05-11-【javascript】js地下城-2f-時鐘.md')['default']
    '20190515-【javascript】js地下城3f-計算機': typeof import('./components/posts/2019-05-15-【javascript】js地下城-3f-計算機.md')['default']
    '20190516-【javascript】js地下城4f-時區': typeof import('./components/posts/2019-05-16-【javascript】js地下城-4f-時區.md')['default']
    '20190517Xmlhttprequest與fetchApi：2019年最適合ajax的是什麼？': typeof import('./components/posts/2019-05-17-xmlhttprequest與fetch-api：2019年最適合ajax的是什麼？.md')['default']
    '20190518-【javascript】js地下城5f-全台空氣指標儀表板': typeof import('./components/posts/2019-05-18-【javascript】js地下城-5f-全台空氣指標儀表板.md')['default']
    '20190522-【javascript】js地下城6f60秒算數遊戲': typeof import('./components/posts/2019-05-22-【javascript】js地下城-6f-60秒算數遊戲.md')['default']
    20190525NodeRedLineBotJpyCurrency: typeof import('./components/posts/2019-05-25-node-red-line-bot-jpy-currency.md')['default']
    '20190530-【javascript】js地下城7f-畫版': typeof import('./components/posts/2019-05-30-【javascript】js地下城-7f-畫版.md')['default']
    20190606MacosNssqliteerrordomain: typeof import('./components/posts/2019-06-06-macos-nssqliteerrordomain.md')['default']
    20190606QuicklookPluginsCommand: typeof import('./components/posts/2019-06-06-quicklook-plugins-command.md')['default']
    20190607VestacpLetsEncrypt: typeof import('./components/posts/2019-06-07-vestacp-lets-encrypt.md')['default']
    '20190618-【JavaScript】js地下城8f-井字遊戲': typeof import('./components/posts/2019-06-18-【JavaScript】js地下城-8f-井字遊戲.md')['default']
    '20190715-日本LineMoblie-申請流程必備書類文件講解！': typeof import('./components/posts/2019-07-15-日本-line-moblie-申請流程必備書類文件講解！.md')['default']
    '20190928-【日本留學】台灣駕照換日本駕照！': typeof import('./components/posts/2019-09-28-【日本留學】台灣駕照換日本駕照！.md')['default']
    '20191003-【javascript】js地下城9f-抽獎轉盤': typeof import('./components/posts/2019-10-03-【javascript】js地下城-9f-抽獎轉盤.md')['default']
    '20191230-【vueJs】veevalidate30-使用方法＆導入中文語系': typeof import('./components/posts/2019-12-30-【vue-js】veevalidate-3-0-使用方法＆導入中文語系.md')['default']
    20200220ChineseDiamondPrincessCovid19: typeof import('./components/posts/2020-02-20-chinese-diamond-princess-covid-19.md')['default']
    20200222Iterm2OhMyZshCobalt2Install: typeof import('./components/posts/2020-02-22-iterm2-oh-my-zsh-cobalt2-install.md')['default']
    20200306MailuMailServerInstall: typeof import('./components/posts/2020-03-06-mailu-mail-server-install.md')['default']
    '20200417ProxmoxLxc-安裝DockerDockerCompose': typeof import('./components/posts/2020-04-17-proxmox-lxc-安裝-docker-docker-compose.md')['default']
    '20200510-使用Iphone-透過無線傳輸當作Webcam！！mac、pc通用': typeof import('./components/posts/2020-05-10-使用-iphone-透過無線傳輸當作-webcam！！mac、pc通用.md')['default']
    '20200702-美波新曲「アメヲマツ、」中文翻譯': typeof import('./components/posts/2020-07-02-美波新曲「アメヲマツ、」中文翻譯.md')['default']
    20210928MyMacOSAppList: typeof import('./components/posts/2021-09-28-My-macOS-App-List.md')['default']
    20210928ReplaceDockerDesktopWithMultipass: typeof import('./components/posts/2021-09-28-Replace-Docker-Desktop-with-Multipass.md')['default']
    AboutMe: typeof import('./components/AboutMe.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    ListPosts: typeof import('./components/ListPosts.vue')['default']
    Post: typeof import('./components/Post.vue')['default']
    Posts: typeof import('./components/posts/index.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShareButtons: typeof import('./components/ShareButtons.vue')['default']
    TagLabel: typeof import('./components/TagLabel.vue')['default']
    TagSelectList: typeof import('./components/TagSelectList.vue')['default']
    ToggleTheme: typeof import('./components/ToggleTheme.vue')['default']
    Transform: typeof import('./components/Transform.vue')['default']
    Tweet: typeof import('./components/Tweet.vue')['default']
    'コンパイラ': typeof import('./components/posts/2021-03-06-Windi CSS：次世代 Tailwind CSS コンパイラ.md')['default']
  }
}
